# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow11.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from threading import Thread
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from computerCam import Camera
from commonUtils import commonUtils

from PyQt5.QtCore import pyqtSlot
from client import Client

import Emotion
from graphics import Graphics

class Ui_MainWindow(object):
    def __init__(self, firstWindow):
        self.MainWindow = firstWindow
        self.setupUi()

    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(1350, 310, 521, 361))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../OneDrive/תמונות/forProject/patches-smiley-face-happy-sad-venn_grande.webp"))
        self.label.setObjectName("label")
        self.playButton = QtWidgets.QPushButton(self.centralwidget)
        self.playButton.setGeometry(QtCore.QRect(620, 430, 571, 221))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.playButton.setFont(font)
        self.playButton.setObjectName("playButton")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(680, 30, 661, 201))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(72)
        font.setItalic(True)
        font.setUnderline(True)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 460, 221, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(80, 520, 181, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(1330, 360, 561, 351))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(
            "../../OneDrive/תמונות/forProject/patches-smiley-face-happy-sad-venn_grande.webp"))
        self.label_4.setObjectName("label_4")
        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2738, 26))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi()

        self.playButton.clicked.connect(Ui_MainWindow.playPressed)
        self.pushButton_2.clicked.connect(Ui_MainWindow.recordsPressed)

        self.MainWindow.setCentralWidget(self.centralwidget)
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)


    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "firstWindow"))
        self.playButton.setText(_translate("MainWindow", "play"))
        self.label_2.setText(_translate("MainWindow", "wiggly face"))
        self.label_3.setText(_translate("MainWindow", "press to see world records:"))
        self.pushButton_2.setText(_translate("MainWindow", "records"))

    def playPressed(self):
        cp = Camera()
        camThread = Thread(target=cp.mainProcess)
        camThread.start()

        gr = Graphics()
        gr.objectsManeger()

    def recordsPressed(self):
        client = Client.get_instance()
        topDict = client.topFive()

        result = ""
        for user, value in topDict.items():
            result += "{:<15} \t {} \n".format(user, commonUtils.get_time_str(value))

        msg = QMessageBox()
        msg.setWindowTitle("records")
        msg.setText("                         THE BEST SCORES IN THE WHOLE GAME:                        ")
        msg.setStandardButtons(QMessageBox.Close)
        msg.setInformativeText(result)

        x = msg.exec_()