# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'singUpWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from userNameClass import UserNameClass
from client import Client
from newNainWindow import Ui_MainWindow
#from PyQt5.QtGui import QRegExpValidator
#from PyQt5.QtCore import QRegExp
from PyQt5.QtWidgets import QMessageBox
import re
from typing import Tuple

class Ui_SignUp(object):
    def __init__(self, firstWindow):
        self.MainWindow = firstWindow
        self.setupUi()


    def setupUi(self):
        self.MainWindow.setObjectName("MainWindow")
        self.MainWindow.showMaximized()
        self.centralwidget = QtWidgets.QWidget(self.MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.signUpLabel = QtWidgets.QLabel(self.centralwidget)
        self.signUpLabel.setGeometry(QtCore.QRect(200, 360, 401, 141))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.signUpLabel.setFont(font)
        self.signUpLabel.setObjectName("signUpLabel")
        self.createYourUsernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.createYourUsernameLabel.setGeometry(QtCore.QRect(200, 530, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.createYourUsernameLabel.setFont(font)
        self.createYourUsernameLabel.setObjectName("createYourUsernameLabel")
        self.passwordLabel = QtWidgets.QLabel(self.centralwidget)

        self.passwordLabel.setGeometry(QtCore.QRect(200, 650, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.passwordLabel.setFont(font)
        self.passwordLabel.setObjectName("passwordLabel")
        self.newUserName = QtWidgets.QLineEdit(self.centralwidget)
        self.newUserName.setGeometry(QtCore.QRect(320, 570, 113, 22))
        self.newUserName.setObjectName("newUserName")

        self.newPassword = QtWidgets.QLineEdit(self.centralwidget)
        self.newPassword.setGeometry(QtCore.QRect(320, 660, 113, 22))
        self.newPassword.setObjectName("newPassword")
        self.newPassword.setEchoMode(QtWidgets.QLineEdit.Password)

        self.usernameLabel = QtWidgets.QLabel(self.centralwidget)
        self.usernameLabel.setGeometry(QtCore.QRect(200, 570, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setObjectName("usernameLabel")

        self.someoneWithThisNameExist = QtWidgets.QLabel(self.centralwidget)
        self.someoneWithThisNameExist.setGeometry(QtCore.QRect(200, 495, 510, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.someoneWithThisNameExist.setFont(font)
        self.someoneWithThisNameExist.setObjectName("wrongUsernameOrPassword")

        self.empty = QtWidgets.QLabel(self.centralwidget)
        self.empty.setGeometry(QtCore.QRect(200, 495, 500, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.empty.setFont(font)
        self.empty.setObjectName("emptyTextBox")

        self.createYourPasswordLabel = QtWidgets.QLabel(self.centralwidget)
        self.createYourPasswordLabel.setGeometry(QtCore.QRect(200, 620, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.createYourPasswordLabel.setFont(font)
        self.createYourPasswordLabel.setObjectName("createYourPasswordLabel")
        self.confirmButton = QtWidgets.QPushButton(self.centralwidget)
        self.confirmButton.setGeometry(QtCore.QRect(540, 630, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.confirmButton.setFont(font)
        self.confirmButton.setObjectName("confirmButton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 650, 55, 16))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../.designer/Screenshot - 1.png"))
        self.label.setObjectName("label")
        self.wigglyFaceCaption = QtWidgets.QLabel(self.centralwidget)
        self.wigglyFaceCaption.setGeometry(QtCore.QRect(740, -10, 581, 331))
        font = QtGui.QFont()
        font.setFamily("Vivaldi")
        font.setPointSize(72)
        font.setItalic(True)
        font.setUnderline(True)
        self.wigglyFaceCaption.setFont(font)
        self.wigglyFaceCaption.setObjectName("wigglyFaceCaption")
        self.picture = QtWidgets.QLabel(self.centralwidget)
        self.picture.setGeometry(QtCore.QRect(1180, 280, 501, 331))
        self.picture.setText("")
        self.picture.setPixmap(QtGui.QPixmap(
            "../../OneDrive/תמונות/forProject/patches-smiley-face-happy-sad-venn_grande.webp"))
        self.picture.setObjectName("picture")
        self.MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(self.MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 3024, 26))
        self.menubar.setObjectName("menubar")
        self.MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(self.MainWindow)
        self.statusbar.setObjectName("statusbar")
        self.MainWindow.setStatusBar(self.statusbar)

        self.confirmButton.clicked.connect(lambda: Ui_SignUp.confirmPressed(self, self.newUserName.text(), self.newPassword.text()))#################################################################
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self.MainWindow)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signUpLabel.setText(_translate("MainWindow", "sign up:"))
        self.createYourUsernameLabel.setText(_translate("MainWindow", "create your username:"))
        self.passwordLabel.setText(_translate("MainWindow", "password:"))
        self.usernameLabel.setText(_translate("MainWindow", "username:"))
        self.empty.setText(_translate("firstWindow", "your username or password is empty, write one and sign up"))
        self.empty.hide()
        self.someoneWithThisNameExist.setText((_translate("firstWindow", "there is someone with the same username in the system, try a different one")))
        self.someoneWithThisNameExist.hide()
        self.createYourPasswordLabel.setText(_translate("MainWindow", "create your password:"))
        self.confirmButton.setText(_translate("MainWindow", "confirm"))
        self.wigglyFaceCaption.setText(_translate("MainWindow", "wiggly face"))


    def confirmPressed(self, username, password):
        if not username or not password:
            self.empty.show()
            self.someoneWithThisNameExist.hide()

        else:

            passValid, errMsg = self.validate_password(password)
            if passValid:
                c = Client.get_instance()
                usernameOfUser = UserNameClass.get_instance()
                notInDB = c.signUp(username, password)
                if notInDB:
                    usernameOfUser.setUserName(username)
                    new_window = Ui_MainWindow(self.MainWindow)
                else:
                    self.empty.hide()
                    self.someoneWithThisNameExist.show()
            else:
                msg = QMessageBox()
                msg.setText(errMsg)
                msg.setStandardButtons(QMessageBox.Close)
                #msg.setInformativeText(errMsg)

                x = msg.exec_()

    def validate_password(self, password) -> Tuple[bool,str]:
        if len(password) < 8:
            return False, "Password should include at least 8 characters"
        if not re.search("[a-z]", password):
            return False, "Password should include at least one lowercase letter"
        if not re.search("[A-Z]", password):
            return False, "Password should include at least one uppercase letter"
        if not re.search("[0-9]", password):
            return False, "Password should include at least one number"
        return True, ""